name: 'Get Release Assets'
description: 'Download GitHub release assets by version with support for regex in asset name search'
branding:
  icon: download
  color: blue

inputs:
  repo:
    description: 'Repository name with owner. For example, houqp/sqlvet'
    default: ${{ github.repository }}
    required: true
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: true
  match:
    description: 'Regex pattern to match asset by name, For example, `foo_linux_amd64$`'
    required: true
  release:
    description: 'Release version to download, default to latest'
    default: latest
    required: true
  rename:
    description: 'Rename downloaded asset'
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/download.sh
      env:
        REPO: ${{ inputs.repo }}
        RELEASE: ${{ inputs.release }}
        GITHUB_PAT: ${{ inputs.token }}
        MATCH: ${{ inputs.match }}
        RENAME: ${{ inputs.rename }}
      shell: bash

