name: 'Get Release Assets'
description: 'Download GitHub release assets by version with support for regex in asset name search'
branding:
  icon: download
  color: blue

inputs:
  repo:
    description: 'Repository name with owner. For example, houqp/sqlvet'
    default: ${{ github.repository }}
    required: true
  token:
    description: >
      Does set's up a CURL command with the provided PAT to get the repos release. 
    default: ${{ github.token }}
    required: true
  match:
    description: 'Regex pattern to match asset by name, For example, `foo_linux_amd64$`'
    required: true
  release:
    description: 'Release version to download, default to latest'
    default: latest
    required: true
  rename:
    description: 'Rename downloaded asset'
    required: true

outputs:
  release:
    description: "The releases' semantic version, i.e. `1.8.3`"

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/download.sh
      env:
        REPO: ${{ inputs.repo }}
        RELEASE: ${{ inputs.release }}
        GITHUB_PAT: ${{ inputs.token }}
        MATCH: ${{ inputs.match }}
        RENAME: ${{ inputs.rename }}
      shell: bash

